### ISSUE TITLE
Build issues with the SSR in Unity 6, SRR not visible

### ISSUE THREAD

**Issue by victorTMRW** [EricHu33/URP_SSR#3]
Are there any limitations with this repo when creating a build in U6?

The SSR works fine in the editor but when building it then the reflections are not visible at all?
I tried all SSR Passes but end up with the same problem on all of them.

**Comment by EricHu33** [comment]
hello, hmm yeah I have not build the repo yet. probably the shader used by the SSR are not all include inside the build (can be found under project setting-> graphics). I'll check it later, thanks for report the issue.

**Comment by victorTMRW** [comment]
> hello, hmm yeah I have not build the repo yet. probably the shader used by the SSR are not all include inside the build (can be found under project setting-> graphics). I'll check it later, thanks for report the issue.

Thanks for the quick reply, I tried to add all three shaders to the graphics but it didnt resolve the issue.

**Comment by EricHu33** [comment]
Hello I've fixed the issue and it should be work now, it's an assembly issue and some code needs to be adjust.
Also the shaders needs to be set as always included

![{4F41B478-B916-498A-BD41-3991DDB87382}](https://github.com/user-attachments/assets/225aaef1-6627-4107-aeb5-9de048d2d03b)

![{9D339A20-53ED-45DE-949C-803E5E7E3895}](https://github.com/user-attachments/assets/67d0f104-42dd-4c47-994e-8389f2cb8608)
